package cl.ipst.sgi.frames;

import cl.ipst.sgi.frames.producto.frmEditarProducto;
import cl.ipst.sgi.frames.producto.frmDeshabilitarProducto;
import cl.ipst.sgi.frames.producto.frmListarProductos;
import cl.ipst.sgi.frames.producto.frmNuevoProducto;
import cl.ipst.sgi.config.ConexionBBDD;
import cl.ipst.sgi.frames.cliente.*;
import cl.ipst.sgi.frames.proveedor.*;
import cl.ipst.sgi.frames.venta.*;
import cl.ipst.sgi.frames.movimiento.*;
import cl.ipst.sgi.frames.tipoproducto.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Roberto Vargas Vargas <rvargas@dparica.cl>
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        miPanel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        Ventas = new javax.swing.JMenu();
        jmiNuevaVenta = new javax.swing.JMenuItem();
        jmiAnularVenta = new javax.swing.JMenuItem();
        jmiListarVenta = new javax.swing.JMenuItem();
        Movimientos = new javax.swing.JMenu();
        jmiNuevoMov = new javax.swing.JMenuItem();
        jmiEditarMov = new javax.swing.JMenuItem();
        jmiListarMov = new javax.swing.JMenuItem();
        Productos = new javax.swing.JMenu();
        jmiNuevoProducto = new javax.swing.JMenuItem();
        jmiEditarProducto = new javax.swing.JMenuItem();
        jmiDesacProducto = new javax.swing.JMenuItem();
        jmiListarProductos = new javax.swing.JMenuItem();
        Tipo_Producto = new javax.swing.JMenu();
        jmiNuevoTipoProd = new javax.swing.JMenuItem();
        jmiEditarTipoProd = new javax.swing.JMenuItem();
        jmiDesacTipoProd = new javax.swing.JMenuItem();
        jmiListarTipoProd = new javax.swing.JMenuItem();
        Proveedores = new javax.swing.JMenu();
        jmiNuevoProveedor = new javax.swing.JMenuItem();
        jmiEditarProveedor = new javax.swing.JMenuItem();
        jmiAnularProveedor = new javax.swing.JMenuItem();
        jmiListarProveedores = new javax.swing.JMenuItem();
        Clientes = new javax.swing.JMenu();
        jmiNuevoCliente = new javax.swing.JMenuItem();
        jmiEditarCliente = new javax.swing.JMenuItem();
        jmiAnularCliente = new javax.swing.JMenuItem();
        jmiListarClientes = new javax.swing.JMenuItem();
        Ayuda = new javax.swing.JMenu();
        jmiProbarConexion = new javax.swing.JMenuItem();
        jmiAyuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout miPanelLayout = new javax.swing.GroupLayout(miPanel);
        miPanel.setLayout(miPanelLayout);
        miPanelLayout.setHorizontalGroup(
            miPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        miPanelLayout.setVerticalGroup(
            miPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 777, Short.MAX_VALUE)
        );

        Ventas.setText("Ventas");

        jmiNuevaVenta.setText("Nueva Venta");
        jmiNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevaVentaActionPerformed(evt);
            }
        });
        Ventas.add(jmiNuevaVenta);

        jmiAnularVenta.setText("Anular Venta");
        jmiAnularVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAnularVentaActionPerformed(evt);
            }
        });
        Ventas.add(jmiAnularVenta);

        jmiListarVenta.setText("Listar Ventas");
        jmiListarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarVentaActionPerformed(evt);
            }
        });
        Ventas.add(jmiListarVenta);

        jMenuBar1.add(Ventas);

        Movimientos.setText("Movimientos");

        jmiNuevoMov.setText("Nuevo Movimiento");
        jmiNuevoMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevoMovActionPerformed(evt);
            }
        });
        Movimientos.add(jmiNuevoMov);

        jmiEditarMov.setText("Editar Movimiento");
        jmiEditarMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEditarMovActionPerformed(evt);
            }
        });
        Movimientos.add(jmiEditarMov);

        jmiListarMov.setText("Listar Movimientos");
        jmiListarMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarMovActionPerformed(evt);
            }
        });
        Movimientos.add(jmiListarMov);

        jMenuBar1.add(Movimientos);

        Productos.setText("Productos");

        jmiNuevoProducto.setText("Nuevo Producto");
        jmiNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevoProductoActionPerformed(evt);
            }
        });
        Productos.add(jmiNuevoProducto);

        jmiEditarProducto.setText("Editar Producto");
        jmiEditarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEditarProductoActionPerformed(evt);
            }
        });
        Productos.add(jmiEditarProducto);

        jmiDesacProducto.setText("Deshabilitar Producto");
        jmiDesacProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDesacProductoActionPerformed(evt);
            }
        });
        Productos.add(jmiDesacProducto);

        jmiListarProductos.setText("Listar Productos");
        jmiListarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarProductosActionPerformed(evt);
            }
        });
        Productos.add(jmiListarProductos);

        jMenuBar1.add(Productos);

        Tipo_Producto.setText("Tipo de Productos");

        jmiNuevoTipoProd.setText("Nuevo Tipo Producto");
        jmiNuevoTipoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevoTipoProdActionPerformed(evt);
            }
        });
        Tipo_Producto.add(jmiNuevoTipoProd);

        jmiEditarTipoProd.setText("Editar Tipo Producto");
        jmiEditarTipoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEditarTipoProdActionPerformed(evt);
            }
        });
        Tipo_Producto.add(jmiEditarTipoProd);

        jmiDesacTipoProd.setText("Desactivar Tipo Producto");
        jmiDesacTipoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDesacTipoProdActionPerformed(evt);
            }
        });
        Tipo_Producto.add(jmiDesacTipoProd);

        jmiListarTipoProd.setText("Listar Tipos de Productos");
        jmiListarTipoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarTipoProdActionPerformed(evt);
            }
        });
        Tipo_Producto.add(jmiListarTipoProd);

        jMenuBar1.add(Tipo_Producto);

        Proveedores.setText("Proveedores");

        jmiNuevoProveedor.setText("Nuevo Proveedor");
        jmiNuevoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevoProveedorActionPerformed(evt);
            }
        });
        Proveedores.add(jmiNuevoProveedor);

        jmiEditarProveedor.setText("Editar Proveedor");
        jmiEditarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEditarProveedorActionPerformed(evt);
            }
        });
        Proveedores.add(jmiEditarProveedor);

        jmiAnularProveedor.setText("Deshabilitar Proveedor");
        jmiAnularProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAnularProveedorActionPerformed(evt);
            }
        });
        Proveedores.add(jmiAnularProveedor);

        jmiListarProveedores.setText("Listar Proveedores");
        jmiListarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarProveedoresActionPerformed(evt);
            }
        });
        Proveedores.add(jmiListarProveedores);

        jMenuBar1.add(Proveedores);

        Clientes.setText("Clientes");

        jmiNuevoCliente.setText("Nuevo Cliente");
        jmiNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNuevoClienteActionPerformed(evt);
            }
        });
        Clientes.add(jmiNuevoCliente);

        jmiEditarCliente.setText("Editar Cliente");
        jmiEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEditarClienteActionPerformed(evt);
            }
        });
        Clientes.add(jmiEditarCliente);

        jmiAnularCliente.setText("Deshabilitar Cliente");
        jmiAnularCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAnularClienteActionPerformed(evt);
            }
        });
        Clientes.add(jmiAnularCliente);

        jmiListarClientes.setText("Listar Clientes");
        jmiListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarClientesActionPerformed(evt);
            }
        });
        Clientes.add(jmiListarClientes);

        jMenuBar1.add(Clientes);

        Ayuda.setText("Ayuda");

        jmiProbarConexion.setText("Probar Conexión a BBDD");
        jmiProbarConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProbarConexionActionPerformed(evt);
            }
        });
        Ayuda.add(jmiProbarConexion);

        jmiAyuda.setText("Acerca de");
        jmiAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAyudaActionPerformed(evt);
            }
        });
        Ayuda.add(jmiAyuda);

        jMenuBar1.add(Ayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(miPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(miPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevaVentaActionPerformed
        frmNuevaVenta v = new frmNuevaVenta();
        miPanel.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_jmiNuevaVentaActionPerformed

    private void jmiAnularVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAnularVentaActionPerformed
        frmAnularVenta v = new frmAnularVenta();
        miPanel.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_jmiAnularVentaActionPerformed

    private void jmiListarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarVentaActionPerformed
        frmListarVentas v = new frmListarVentas();
        miPanel.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_jmiListarVentaActionPerformed

    private void jmiNuevoMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevoMovActionPerformed
        frmNuevoMovimiento v = new frmNuevoMovimiento();
        miPanel.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_jmiNuevoMovActionPerformed

    private void jmiEditarMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEditarMovActionPerformed
        frmEditarMovimiento v = new frmEditarMovimiento();
        miPanel.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_jmiEditarMovActionPerformed

    private void jmiListarMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarMovActionPerformed
        frmListarMovimientos v = new frmListarMovimientos();
        miPanel.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_jmiListarMovActionPerformed

    private void jmiNuevoTipoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevoTipoProdActionPerformed
        frmNuevoTipoProducto v = new frmNuevoTipoProducto();
        miPanel.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_jmiNuevoTipoProdActionPerformed

    private void jmiEditarTipoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEditarTipoProdActionPerformed
        frmEditarTipoProducto v = new frmEditarTipoProducto();
        miPanel.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_jmiEditarTipoProdActionPerformed

    private void jmiDesacTipoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDesacTipoProdActionPerformed
        frmDeshabilitarTipoProducto v = new frmDeshabilitarTipoProducto();
        miPanel.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_jmiDesacTipoProdActionPerformed

    private void jmiListarTipoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarTipoProdActionPerformed
        frmListarTiposProductos v = new frmListarTiposProductos();
        miPanel.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_jmiListarTipoProdActionPerformed

    private void jmiNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevoProductoActionPerformed
        frmNuevoProducto v = new frmNuevoProducto();
        miPanel.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_jmiNuevoProductoActionPerformed

    private void jmiEditarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEditarProductoActionPerformed
        frmEditarProducto v = new frmEditarProducto();
        miPanel.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_jmiEditarProductoActionPerformed

    private void jmiDesacProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDesacProductoActionPerformed
        frmDeshabilitarProducto v = new frmDeshabilitarProducto();
        miPanel.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_jmiDesacProductoActionPerformed

    private void jmiListarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarProductosActionPerformed
        frmListarProductos v = new frmListarProductos();
        miPanel.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_jmiListarProductosActionPerformed

    private void jmiNuevoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevoProveedorActionPerformed
        frmNuevoProveedor v = new frmNuevoProveedor();
        miPanel.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_jmiNuevoProveedorActionPerformed

    private void jmiEditarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEditarProveedorActionPerformed
        frmEditarProveedor v = new frmEditarProveedor();
        miPanel.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_jmiEditarProveedorActionPerformed

    private void jmiAnularProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAnularProveedorActionPerformed
        frmDeshabilitarProveedor v = new frmDeshabilitarProveedor();
        miPanel.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_jmiAnularProveedorActionPerformed

    private void jmiListarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarProveedoresActionPerformed
        frmListarProveedores v = new frmListarProveedores();
        miPanel.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_jmiListarProveedoresActionPerformed

    private void jmiNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNuevoClienteActionPerformed
        frmNuevoCliente v = new frmNuevoCliente();
        miPanel.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_jmiNuevoClienteActionPerformed

    private void jmiEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEditarClienteActionPerformed
        frmEditarCliente v = new frmEditarCliente();
        miPanel.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_jmiEditarClienteActionPerformed

    private void jmiAnularClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAnularClienteActionPerformed
        frmDeshabilitarCliente v = new frmDeshabilitarCliente();
        miPanel.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_jmiAnularClienteActionPerformed

    private void jmiListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarClientesActionPerformed
        frmListarClientes v = new frmListarClientes();
        miPanel.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_jmiListarClientesActionPerformed

    private void jmiAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAyudaActionPerformed
        ImageIcon icono = new ImageIcon(getClass().getResource("/cl/ipst/sgi/resources/images/ipst.png"));
        String mensaje = "<html><div style='text-align: center;'>"
                + "<b>Sistema de Gestión de Inventario</b><br>"
                + "<hr>"
                + "Programadores: <br>"
                + "Issel Cruz <br>"
                + "Tamara Quispe <br>"
                + "Katherine Vilca <br>"
                + "Roberto Vargas <br>"
                + "<br>"
                + "Integración de Competencias I<br>"
                + "Instituto Profesional Santo Tomás - Sede Arica"
                + "</div></html>";

        JOptionPane.showMessageDialog(null, mensaje,
                "Sistema de Gestión de Inventario", JOptionPane.INFORMATION_MESSAGE, icono);
    }//GEN-LAST:event_jmiAyudaActionPerformed

    private void jmiProbarConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProbarConexionActionPerformed
        //Test de conexión
        ConexionBBDD conexion = new ConexionBBDD();
        conexion.probarConexion();
    }//GEN-LAST:event_jmiProbarConexionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Ayuda;
    private javax.swing.JMenu Clientes;
    private javax.swing.JMenu Movimientos;
    private javax.swing.JMenu Productos;
    private javax.swing.JMenu Proveedores;
    private javax.swing.JMenu Tipo_Producto;
    private javax.swing.JMenu Ventas;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiAnularCliente;
    private javax.swing.JMenuItem jmiAnularProveedor;
    private javax.swing.JMenuItem jmiAnularVenta;
    private javax.swing.JMenuItem jmiAyuda;
    private javax.swing.JMenuItem jmiDesacProducto;
    private javax.swing.JMenuItem jmiDesacTipoProd;
    private javax.swing.JMenuItem jmiEditarCliente;
    private javax.swing.JMenuItem jmiEditarMov;
    private javax.swing.JMenuItem jmiEditarProducto;
    private javax.swing.JMenuItem jmiEditarProveedor;
    private javax.swing.JMenuItem jmiEditarTipoProd;
    private javax.swing.JMenuItem jmiListarClientes;
    private javax.swing.JMenuItem jmiListarMov;
    private javax.swing.JMenuItem jmiListarProductos;
    private javax.swing.JMenuItem jmiListarProveedores;
    private javax.swing.JMenuItem jmiListarTipoProd;
    private javax.swing.JMenuItem jmiListarVenta;
    private javax.swing.JMenuItem jmiNuevaVenta;
    private javax.swing.JMenuItem jmiNuevoCliente;
    private javax.swing.JMenuItem jmiNuevoMov;
    private javax.swing.JMenuItem jmiNuevoProducto;
    private javax.swing.JMenuItem jmiNuevoProveedor;
    private javax.swing.JMenuItem jmiNuevoTipoProd;
    private javax.swing.JMenuItem jmiProbarConexion;
    private javax.swing.JDesktopPane miPanel;
    // End of variables declaration//GEN-END:variables
}
